module.exports = {
  apps: [
    {
      name: 'paperclip-web',
      script: './server/dist/index.js',
      cwd: '/Users/mia/.openclaw/workspace/05-PROJETOS/paperclip',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '3001',
        SERVE_UI: 'false',
        PAPERCLIP_MIGRATION_PROMPT: 'never',
        PAPERCLIP_MIGRATION_AUTO_APPLY: 'true',
        PAPERCLIP_DEPLOYMENT_MODE: 'authenticated',
        PAPERCLIP_DEPLOYMENT_EXPOSURE: 'private',
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'paperclip-worker',
      script: './server/dist/worker.js',
      cwd: '/Users/mia/.openclaw/workspace/05-PROJETOS/paperclip',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        WORKER_TYPE: 'background',
        PAPERCLIP_DEPLOYMENT_MODE: 'authenticated',
      },
      error_file: './logs/worker-err.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
