module.exports = {
  apps: [
    {
      name: "paperclip-web",
      script: "./server/dist/index.js",
      cwd: "/Users/mia/.openclaw/workspace/05-PROJETOS/paperclip",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3100,
      },
      env_file: ".env",
      log_file: "./logs/web-out.log",
      out_file: "./logs/web-out.log",
      error_file: "./logs/web-err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      autorestart: true,
      watch: false,
      ignore_watch: ["node_modules", "logs", "data"],
      kill_timeout: 5000,
      listen_timeout: 10000,
      source_map_support: true,
    },
    {
      name: "paperclip-worker",
      script: "./server/dist/worker.js",
      cwd: "/Users/mia/.openclaw/workspace/05-PROJETOS/paperclip",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        WORKER_TYPE: "background",
      },
      env_file: ".env",
      log_file: "./logs/worker-out.log",
      out_file: "./logs/worker-out.log",
      error_file: "./logs/worker-err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "512M",
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
      autorestart: true,
      watch: false,
      ignore_watch: ["node_modules", "logs", "data"],
      kill_timeout: 5000,
    },
  ],
};
